// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Optimeas GmbH

//! Generate the `bcMessageEvent` reference pair into `examples/generated/`:
//!
//! - `osf4_message_event_string.osf` — deployed-firmware encoding: the
//!   `Demo.Message` string channel is written as `bcMessageEvent` (control
//!   byte 4), the deprecated block type every reader in this repository
//!   currently skips (OSF-UP4).
//! - `osf4_message_event_string_equivalent.osf` — the same two channels
//!   with the same sample content, but with `Demo.Message` written as
//!   `bcAbsTimeStampData` (control byte 8) instead, the block type every
//!   reader already understands.
//!
//! The two files must decode channel for channel to the same result: same
//! `Demo.Counter` values, same `Demo.Message` timestamps and text. The
//! *only* difference is the wire encoding of the string channel — that
//! difference is the entire point of the pair, since it is what lets a
//! reader test prove "these two are equivalent" once `bcMessageEvent`
//! support lands.
//!
//! No writer in this crate — nor in any of the other four reference
//! implementations — emits control byte 4, and per OSF-UP4 none of them
//! ever should: `bcMessageEvent` is a deprecated relic of pre-2026-05-04
//! firmware. So unlike most of this crate's example generators, which
//! call `WriterBuilder`, the message-event file is assembled byte by
//! byte here, and its `bcAbsTimeStampData` sibling is assembled the same
//! way for a direct, mechanical comparison between the two encodings.
//!
//! ## The deliberate asymmetry
//!
//! The two string-block wire formats are *not* mirror images of each
//! other:
//!
//! ```text
//! bcMessageEvent (byte 4):        [u16 idx][u32 len][0x04][i64 ts][u32 N][N bytes]
//! bcAbsTimeStampData (byte 8):    [u16 idx][u32 len][0x08][i64 ts][payload bytes][0x00]
//! ```
//!
//! `bcMessageEvent`'s payload is explicitly length-prefixed (the `u32 N`
//! immediately before the bytes), so it carries no terminator — the
//! length field already says exactly how many payload bytes follow.
//! `bcAbsTimeStampData` in OSF4 has no such length prefix for its string
//! payload; instead OSF4 always appends a trailing `0x00`, and a
//! conforming OSF4 reader strips exactly one trailing byte unconditionally
//! (spec rev 2026-05-24, cross-implementation null-terminator rule). Get
//! this backwards in the generator and the byte-identity check below
//! catches it immediately (see "mismatches hit" in the commit that added
//! this file).
//!
//! `Demo.Counter` (a plain `uint32` channel) is encoded identically in
//! both files: `bcAbsTimeStampData`, control byte `0x08` with bit 7
//! *clear* (single sample per block, no leading count) — confirmed against
//! both committed files byte for byte; it has nothing to do with the
//! string-channel comparison the pair exists for.
//!
//! ## Central constraint
//!
//! Both `.osf` files already exist in the repository, hand-verified
//! against real field recordings. This generator's job is to *reproduce*
//! them, not to replace them. If the generated bytes differ from a
//! committed file, the generator is the suspect, not the file: it prints
//! a diagnostic and exits non-zero rather than overwriting anything. Only
//! evidence that a committed file is actually wrong would justify
//! replacing it, and that never happened while writing this generator.
//!
//! ## Why `Demo.Message` is not asserted for the message-event file
//!
//! Every reader in this crate currently routes control byte 4 to
//! `SkipReason::DeprecatedBlockType` (OSF-UP4 is a normative-spec-only
//! change so far; the reader change is a later task). So as of this
//! generator, `osf4_message_event_string.osf` decodes `Demo.Message` to
//! zero samples — correctly, given today's reader — while
//! `osf4_message_event_string_equivalent.osf` already decodes it in full.
//! The self-verification below therefore checks `Demo.Counter` (works in
//! both files today) and the exact block-accounting stats (which capture
//! the skip behaviour precisely) for the message-event file, and checks
//! both channels in full for the equivalent file. Once a later task adds
//! `bcMessageEvent` parsing, that task's own reader test is the place to
//! assert `Demo.Message` content for the message-event file — duplicating
//! that assertion here, before the parser exists, would only ever fail.
//!
//! Run with `cargo run --example gen_message_event_refs`.

use osf_core::{Channel, DataManager};
use std::path::{Path, PathBuf};

// ---------------------------------------------------------------------
// Shared sample data - the single source of truth both files encode.
// ---------------------------------------------------------------------

/// First sample's absolute timestamp, nanoseconds since the Unix epoch.
const BASE_TIMESTAMP_NS: i64 = 1_768_478_400_000_000_000;
/// Spacing between samples, in nanoseconds (5 seconds).
const TIMESTAMP_STEP_NS: i64 = 5_000_000_000;

/// `Demo.Counter` sample values, in stream order.
const COUNTER_VALUES: [u32; 5] = [10, 20, 30, 40, 50];

/// The fifth `Demo.Message` sample: 300 repetitions of `'A'`, forcing the
/// length field comfortably past a single byte. Built with `concat!` (six
/// 50-byte chunks) so it stays a compile-time `&'static str` alongside the
/// other four literals, rather than a runtime `"A".repeat(300)`.
const LONG_MESSAGE: &str = concat!(
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
);

/// `Demo.Message` sample texts, in stream order. Exercises: a normal
/// string, another normal string, an empty string, a non-ASCII string
/// (UTF-8 multi-byte + a symbol), and the 300-byte long string above.
const MESSAGE_TEXTS: [&str; 5] = [
    "OSF-DEMO-0001",
    "no signal",
    "",
    "Grüße aus Säckingen ✓",
    LONG_MESSAGE,
];

/// Channel index of `Demo.Counter` (declared first in the metablock).
const COUNTER_CHANNEL_INDEX: u16 = 0;
/// Channel index of `Demo.Message` (declared second in the metablock).
const MESSAGE_CHANNEL_INDEX: u16 = 1;

/// `created_utc` timestamps as they were stamped into the two committed
/// files at generation time. These are not reproducible from the current
/// clock - they are literal facts about the corpus files being
/// reproduced, exactly like every other byte in the metablock.
const CREATED_UTC_MESSAGE_EVENT: &str = "2026-07-28T18:29:32.047Z";
const CREATED_UTC_EQUIVALENT: &str = "2026-07-28T18:29:32.058Z";

fn generated_dir() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // .../implementations/rust/osf-core -> repo root
    p.pop();
    p.pop();
    p.pop();
    p.join("examples").join("generated")
}

// ---------------------------------------------------------------------
// Byte-level block builders.
// ---------------------------------------------------------------------

/// One `Demo.Counter` block: `bcAbsTimeStampData` (control byte `0x08`,
/// bit 7 clear - single sample), 2-byte length field (matches the
/// channel's `sizeoflengthvalue="2"`).
///
/// Wire layout: `[u16 idx][u16 len][0x08][i64 ts][u32 value]`, where
/// `len = 1 (ctrl) + 8 (ts) + 4 (value) = 13`.
fn counter_block(timestamp_ns: i64, value: u32) -> Vec<u8> {
    let mut out = Vec::with_capacity(2 + 2 + 1 + 8 + 4);
    out.extend_from_slice(&COUNTER_CHANNEL_INDEX.to_le_bytes());
    let length: u16 = 1 + 8 + 4;
    out.extend_from_slice(&length.to_le_bytes());
    out.push(0x08); // bcAbsTimeStampData, bit 7 clear.
    out.extend_from_slice(&timestamp_ns.to_le_bytes());
    out.extend_from_slice(&value.to_le_bytes());
    out
}

/// One `Demo.Message` block encoded as `bcMessageEvent` (control byte
/// `0x04`) - the deployed-firmware encoding. 4-byte length field (matches
/// `sizeoflengthvalue="4"`).
///
/// Wire layout: `[u16 idx][u32 len][0x04][i64 ts][u32 N][N bytes]`, where
/// `len = 1 (ctrl) + 8 (ts) + 4 (N) + N`. No terminator: the payload is
/// already length-prefixed by `N`.
fn message_event_block(timestamp_ns: i64, text: &str) -> Vec<u8> {
    let payload = text.as_bytes();
    let n = u32::try_from(payload.len()).expect("message payload fits in u32");
    let mut out = Vec::with_capacity(2 + 4 + 1 + 8 + 4 + payload.len());
    out.extend_from_slice(&MESSAGE_CHANNEL_INDEX.to_le_bytes());
    let length: u32 = 1 + 8 + 4 + n;
    out.extend_from_slice(&length.to_le_bytes());
    out.push(0x04); // bcMessageEvent.
    out.extend_from_slice(&timestamp_ns.to_le_bytes());
    out.extend_from_slice(&n.to_le_bytes());
    out.extend_from_slice(payload);
    out
}

/// One `Demo.Message` block encoded as `bcAbsTimeStampData` (control byte
/// `0x08`) - the already-supported equivalent encoding. 4-byte length
/// field (matches `sizeoflengthvalue="4"`).
///
/// Wire layout: `[u16 idx][u32 len][0x08][i64 ts][payload bytes][0x00]`,
/// where `len = 1 (ctrl) + 8 (ts) + payload.len() + 1 (terminator)`. OSF4
/// always appends the trailing `0x00` for string/binary
/// `bcAbsTimeStampData` payloads (spec rev 2026-05-04); this is the
/// asymmetry documented in the module doc comment above.
fn legacy_string_block(timestamp_ns: i64, text: &str) -> Vec<u8> {
    let payload = text.as_bytes();
    let payload_len = u32::try_from(payload.len()).expect("message payload fits in u32");
    let mut out = Vec::with_capacity(2 + 4 + 1 + 8 + payload.len() + 1);
    out.extend_from_slice(&MESSAGE_CHANNEL_INDEX.to_le_bytes());
    let length: u32 = 1 + 8 + payload_len + 1;
    out.extend_from_slice(&length.to_le_bytes());
    out.push(0x08); // bcAbsTimeStampData.
    out.extend_from_slice(&timestamp_ns.to_le_bytes());
    out.extend_from_slice(payload);
    out.push(0x00); // OSF4 terminator - present here, absent above.
    out
}

/// The shared metablock XML body, parameterized only by `created_utc`
/// (the one byte range that legitimately differs between the two
/// committed files - everything else about the channel declarations is
/// identical, confirmed by diffing the two files' metablocks byte for
/// byte).
fn metablock_xml(created_utc: &str) -> String {
    // Deliberately one literal (no line-continuation backslashes): Rust
    // strips all leading whitespace after a `\`-continued newline inside a
    // string literal, which would silently eat the 2- and 4-space XML
    // indentation this text needs to match byte for byte.
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<optimeas creator=\"\" created_utc=\"{created_utc}\" namespacesep=\".\">\n  <channels count=\"2\">\n    <channel index=\"0\" name=\"Demo.Counter\" channeltype=\"scalar\" datatype=\"uint32\" sizeoflengthvalue=\"2\"/>\n    <channel index=\"1\" name=\"Demo.Message\" channeltype=\"scalar\" datatype=\"string\" sizeoflengthvalue=\"4\"/>\n  </channels>\n</optimeas>\n"
    )
}

/// Assemble a full OSF4 file: magic header line, metablock, block
/// section.
fn assemble_file(created_utc: &str, block_section: &[u8]) -> Vec<u8> {
    let metablock = metablock_xml(created_utc);
    let mut out = Vec::with_capacity(16 + metablock.len() + block_section.len());
    out.extend_from_slice(format!("OSF4 {}\n", metablock.len()).as_bytes());
    out.extend_from_slice(metablock.as_bytes());
    out.extend_from_slice(block_section);
    out
}

// ---------------------------------------------------------------------
// File builders.
// ---------------------------------------------------------------------

/// `osf4_message_event_string.osf`: all five `Demo.Counter` blocks, then
/// all five `Demo.Message` blocks (channel-major ordering) - confirmed
/// against the committed file, which is not interleaved by sample index.
fn build_message_event_file() -> Vec<u8> {
    let mut blocks = Vec::new();
    for i in 0..5i64 {
        let ts = BASE_TIMESTAMP_NS + i * TIMESTAMP_STEP_NS;
        blocks.extend_from_slice(&counter_block(ts, COUNTER_VALUES[i as usize]));
    }
    for i in 0..5i64 {
        let ts = BASE_TIMESTAMP_NS + i * TIMESTAMP_STEP_NS;
        blocks.extend_from_slice(&message_event_block(ts, MESSAGE_TEXTS[i as usize]));
    }
    assemble_file(CREATED_UTC_MESSAGE_EVENT, &blocks)
}

/// `osf4_message_event_string_equivalent.osf`: `Demo.Counter` and
/// `Demo.Message` blocks interleaved sample by sample (round-robin
/// ordering) - confirmed against the committed file, which alternates
/// channel 0 then channel 1 for each sample index rather than grouping by
/// channel. This is a real, independently-observed difference from the
/// message-event file's channel-major ordering, not an inconsistency in
/// this generator.
fn build_equivalent_file() -> Vec<u8> {
    let mut blocks = Vec::new();
    for i in 0..5i64 {
        let ts = BASE_TIMESTAMP_NS + i * TIMESTAMP_STEP_NS;
        blocks.extend_from_slice(&counter_block(ts, COUNTER_VALUES[i as usize]));
        blocks.extend_from_slice(&legacy_string_block(ts, MESSAGE_TEXTS[i as usize]));
    }
    assemble_file(CREATED_UTC_EQUIVALENT, &blocks)
}

// ---------------------------------------------------------------------
// Compare-or-write with a loud failure on mismatch.
// ---------------------------------------------------------------------

/// Write `bytes` to `path` only if `path` does not already exist. If it
/// does exist, compare byte for byte: report and keep the committed file
/// on any difference (exit non-zero, no overwrite), or confirm the match.
///
/// This is the central constraint for this generator: the committed
/// files were hand-verified against real field recordings, so a mismatch
/// means *this generator* has a bug, not that the committed file is
/// wrong.
fn compare_or_write(path: &Path, bytes: &[u8]) {
    match std::fs::read(path) {
        Ok(existing) => {
            if existing == bytes {
                println!(
                    "byte-identical: {} ({} bytes)",
                    path.display(),
                    bytes.len()
                );
            } else {
                eprintln!(
                    "MISMATCH: generated bytes differ from the committed reference file.\n\
                     \x20 file:      {}\n\
                     \x20 committed: {} bytes\n\
                     \x20 generated: {} bytes\n\
                     \x20 The committed file was hand-verified against a real field \
                     recording; this generator did not reproduce it and is therefore \
                     the suspect, not the file. The file was left untouched. \
                     Investigate the byte layout (diff the two buffers) and fix the \
                     generator - do not overwrite.",
                    path.display(),
                    existing.len(),
                    bytes.len()
                );
                std::process::exit(1);
            }
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            std::fs::write(path, bytes).expect("write new reference file");
            println!("wrote (new file): {} ({} bytes)", path.display(), bytes.len());
        }
        Err(e) => {
            eprintln!("failed to read {}: {e}", path.display());
            std::process::exit(1);
        }
    }
}

// ---------------------------------------------------------------------
// Self-verification: load the generated files back through DataManager.
// ---------------------------------------------------------------------

/// Assert `Demo.Counter` decodes to the five expected `(timestamp,
/// value)` pairs. Shared between both files - the counter channel is
/// encoded identically in each and must decode identically in each.
fn assert_counter_channel(mgr: &DataManager, file_label: &str) {
    let ch = mgr
        .channel("Demo.Counter")
        .unwrap_or_else(|| panic!("{file_label}: Demo.Counter channel missing"));
    let Channel::Timestamped(tc) = ch else {
        panic!("{file_label}: Demo.Counter unexpectedly not a timestamped channel");
    };
    let decoded = tc
        .as_uint32_flat()
        .unwrap_or_else(|e| panic!("{file_label}: Demo.Counter not uint32: {e}"));
    let expected: Vec<(i64, u32)> = (0..5i64)
        .map(|i| (BASE_TIMESTAMP_NS + i * TIMESTAMP_STEP_NS, COUNTER_VALUES[i as usize]))
        .collect();
    assert_eq!(
        decoded, expected,
        "{file_label}: Demo.Counter samples do not match the expected sequence"
    );
}

/// Assert `Demo.Message` decodes to the five expected `(timestamp, text)`
/// pairs. Only valid for the equivalent file, where every block already
/// parses today - see the module doc comment for why the message-event
/// file is not asserted here.
fn assert_message_channel(mgr: &DataManager, file_label: &str) {
    let ch = mgr
        .channel("Demo.Message")
        .unwrap_or_else(|| panic!("{file_label}: Demo.Message channel missing"));
    let Channel::Variable(vc) = ch else {
        panic!("{file_label}: Demo.Message unexpectedly not a variable channel");
    };
    let texts = vc
        .as_strings()
        .unwrap_or_else(|e| panic!("{file_label}: Demo.Message not string: {e}"));
    let timestamps = vc.timestamps_ns();
    let decoded: Vec<(i64, &str)> = timestamps
        .iter()
        .copied()
        .zip(texts.iter().map(String::as_str))
        .collect();
    let expected: Vec<(i64, &str)> = (0..5i64)
        .map(|i| (BASE_TIMESTAMP_NS + i * TIMESTAMP_STEP_NS, MESSAGE_TEXTS[i as usize]))
        .collect();
    assert_eq!(
        decoded, expected,
        "{file_label}: Demo.Message samples do not match the expected sequence"
    );
}

fn verify_message_event_file(path: &Path) {
    let mgr = DataManager::load_from_file(path).expect("message-event file loads");
    assert_counter_channel(&mgr, "message-event file");

    // Demo.Message cannot be asserted here yet: today's reader routes
    // every bcMessageEvent block (control byte 4) to
    // SkipReason::DeprecatedBlockType, so the channel decodes to zero
    // samples. That is correct current behaviour, not a bug in this
    // file or this generator - see the module doc comment. What *can*
    // be pinned down today is the exact block accounting: 10 blocks
    // total (5 counter + 5 message), 5 read, 5 skipped as deprecated,
    // nothing else skipped or truncated.
    let stats = &mgr.stats;
    assert_eq!(stats.blocks_total, 10, "expected 5 counter + 5 message blocks");
    assert_eq!(stats.blocks_read, 5, "expected only the 5 counter blocks read");
    assert_eq!(
        stats.blocks_skipped_deprecated_type, 5,
        "expected all 5 bcMessageEvent blocks skipped as deprecated"
    );
    assert_eq!(stats.blocks_skipped_unsupported, 0);
    assert_eq!(stats.blocks_skipped_reserved_type, 0);
    assert_eq!(stats.blocks_skipped_zero_length, 0);
    assert_eq!(stats.blocks_truncated, 0);

    let ch = mgr.channel("Demo.Message").expect("Demo.Message declared");
    let Channel::Variable(vc) = ch else {
        panic!("Demo.Message unexpectedly not a variable channel");
    };
    assert_eq!(
        vc.timestamps_ns().len(),
        0,
        "Demo.Message should decode to 0 samples until bcMessageEvent parsing lands"
    );

    println!("verified: {} (Demo.Counter + block accounting)", path.display());
}

fn verify_equivalent_file(path: &Path) {
    let mgr = DataManager::load_from_file(path).expect("equivalent file loads");
    assert_counter_channel(&mgr, "equivalent file");
    assert_message_channel(&mgr, "equivalent file");

    let stats = &mgr.stats;
    assert_eq!(stats.blocks_total, 10, "expected 5 counter + 5 message blocks");
    assert_eq!(stats.blocks_read, 10, "expected all 10 blocks read");
    assert_eq!(stats.blocks_skipped_deprecated_type, 0);
    assert_eq!(stats.blocks_skipped_unsupported, 0);
    assert_eq!(stats.blocks_skipped_reserved_type, 0);
    assert_eq!(stats.blocks_skipped_zero_length, 0);
    assert_eq!(stats.blocks_truncated, 0);

    println!(
        "verified: {} (Demo.Counter + Demo.Message)",
        path.display()
    );
}

fn main() {
    let dir = generated_dir();
    std::fs::create_dir_all(&dir).expect("create examples/generated dir");

    let message_event_path = dir.join("osf4_message_event_string.osf");
    let equivalent_path = dir.join("osf4_message_event_string_equivalent.osf");

    compare_or_write(&message_event_path, &build_message_event_file());
    compare_or_write(&equivalent_path, &build_equivalent_file());

    verify_message_event_file(&message_event_path);
    verify_equivalent_file(&equivalent_path);
}
